module MyLinearAlgebra
import Base: *, show
export LDU
using LinearAlgebra
using Polynomials
using SparseArrays
using GaloisFields
using Infinity

const F=@GaloisField 2

Base.abs(x::F)=x.n


function Base.divrem(x1::F,x2::F)
	if x2 == F(1)
		return (x1, F(0))
	else
		throw(DivideError)
	end
end

function isunit(x::Int)
	return x==1 || x==-1
end

function isunit(x::Polynomial{T}) where {T}
	return degree(x)==0 && x!= zero(Polynomial{T})
end

#=
macro assert(expr)
end
=#

function is_unit(x::T) where {T}
	return x==one(T) || x==-one(T)
end

function eye(T,m,n)
	@assert m==n
	return Matrix(Diagonal(ones(T,m)))
end

function LDU(A::Array{T,2}) where {T}
	m,n=size(A)
	L,D,U,Linv,Uinv = eye(T,m,m),copy(A),eye(T,n,n), eye(T,m,m), eye(T,n,n)
	LDU!(L,D,U,Linv,Uinv)

	@assert L*D*U==A
	@assert U*Uinv==eye(T,n,n)
	@assert Linv*L==eye(T,m,m)
	for i in 1:m, j in 1:n
		if i!=j
			@assert D[i,j]==zero(T)
		end
	end
	return L,D,U, Linv,Uinv
end

euclidean_norm(x::Polynomial) = degree(x)
euclidean_norm(x::Number) = abs(x)

function *(x::T, A::Array{T}) where {T<:Polynomial}
	return T[x*y for y in A]
end

#const Big = typemax(BigInt)

#Works only over a Euclidean domain
function LDU!(_L::AbstractMatrix{T},_D::AbstractMatrix{T},_U::AbstractMatrix{T}, _Linv::AbstractMatrix{T}, _Uinv::AbstractMatrix{T}) where {T}
	Big = (T==Int ? typemax(Int) : PosInf)
	L=@view _L[:,:]
	D=@view _D[:,:]
	U=@view _U[:,:]
	Linv=@view _Linv[:,:]
	Uinv=@view _Uinv[:,:]

	while size(D)[1] > 0 && size(D)[2] > 0
		#check=L*D*U
		m,n=size(D)
		if m==0 || n==0
			return nothing
		end

		changed = true

		#@assert Linv*L == eye(T,m,m)
		#@assert U*Uinv == eye(T,n,n)

		while changed == true
			changed = false
			norms = map(x->x != zero(T) ? euclidean_norm(x) : Big, D[1,:])
			min_norm, i = findmin(norms)
			if min_norm < Big
				pivot = D[1,i]

				#@assert L*D*U == check
				for j in 1:n
					if i!= j && D[1,j] != zero(T)
						d,r = divrem(D[1,j], pivot)
						D[:,j] .-= d .* D[:,i]
						U[i,:] .+= d .* U[j,:]

						Uinv[:,j] .-= d .* Uinv[:,i]
						changed=true
					end
					#@assert Linv*L == eye(T,m,m)
					#@assert U*Uinv == eye(T,n,n)
				end

				if i!= 1
					D[:,1], D[:,i] = D[:,i], D[:,1]
					U[1,:], U[i,:] = U[i,:], U[1,:]
					Uinv[:,1], Uinv[:,i] = Uinv[:,i], Uinv[:,1]
					#@assert Linv*L == eye(T,m,m)
					#@assert U*Uinv == eye(T,n,n)
					changed=true
				end
			end

			norms = map(x->x!=zero(T) ? euclidean_norm(x) : Big, D[:,1])
			min_norm, i=findmin(norms)
			if min_norm < Big
				pivot = D[i,1]

				#@assert L*D*U == check
				for j in 1:m
					if i!= j && D[j,1] != zero(T)
						d,r = divrem(D[j,1], pivot)
						D[j,:] .-= d.*D[i,:]
						L[:,i] .+= d.*L[:,j]
						Linv[j,:] .-= d.*Linv[i,:]
						changed=true
						#@assert Linv*L == eye(T,m,m)
						#@assert U*Uinv == eye(T,n,n)
					end
				end

				if i!=1
					D[1,:], D[i,:] = D[i,:], D[1,:]
					L[:,1], L[:,i] = L[:,i], L[:,1]
					Linv[1,:], Linv[i,:] = Linv[i,:], Linv[1,:]
					changed=true
					#@assert Linv*L == eye(T,m,m)
					#@assert U*Uinv == eye(T,n,n)
				end
			end
		end

		L=@view L[:,2:end]
		D=@view D[2:end,2:end]
		U=@view U[2:end,:]
		Linv=@view Linv[2:end,:]
		Uinv=@view Uinv[:,2:end]
		#@assert L*D*U == check
		#LDU!((@view L[:,2:end]), (@view D[2:end,2:end]), (@view U[2:end,:]), (@view Linv[2:end,:]), (@view Uinv[:,2:end]))
		#@assert L*D*U == check
	end
end

function my_times(A,B)
	return A*B
	#return full(At_mul_B(sparse(transpose(A)),sparse(B)))
end

function homology(d_matrix::AbstractArray{T,2}) where {T}
	@assert size(d_matrix,1)==size(d_matrix,2)
	n = size(d_matrix,1)
	@assert d_matrix ^2 == fill(zero(T),(n,n))

	#myprintln(d_matrix)
	L,D,U,Linv,Uinv=LDU(d_matrix)
	#LinearAlgebra.myprintln(D)
	#myprintln(D)
	@assert L*D*U==d_matrix
	@assert U*Uinv==eye(T,n,n)
	@assert Linv*L==eye(T,n,n)

	#We work in the basis given by U
	#The kernel of d is generated by the nonzero elements in mask
	#Each element of U*d_matrix gives a relation among these generators
	mask = Bool[D[i,i]==zero(T) ? true : false for i in 1:n]
	relations = my_times(U,d_matrix)[mask,:]
	m=size(relations,1)
	#myprintln(relations)

	@assert d_matrix*Uinv[:,mask] == zeros(T,n,sum(mask))

	pL,pD,pU,pLinv,pUinv=LDU(relations)
	@assert pU*pUinv==eye(T,n,n)
	@assert pLinv*pL==eye(T,m,m)
	@assert pL*pD*pU==relations

	#finally, the homology is generated by 
	generators = my_times(Uinv[:,mask],pL)
	#myprintln(generators)
	#myprintln(pD)

	indices = filter(i->!is_unit(pD[i,i]), 1:m)
	return diag(pD)[indices], generators[:,indices]
end

function cokernel(p_matrix::AbstractArray{T,2}) where {T}
	L,D,U,Linv,Uinv = LDU(p_matrix)
	#return filter(x->!isunit(x), diag(D))
	return diag(D)
end

myprintln(x) = begin show(IOContext(stdout, limit=true), "text/plain", x); println(); end
#D=[2 4 4; -6 6 12; 10 -4 -16]
#map(myprintln,LDU(D))

#=
function show(io::IO, mimetype::MIME"text/plain", p::Poly{T}) where {T}
    Polynomials.printpoly(io, p, mimetype)
end
=#

end
